### ISSUE TITLE
`jekyll serve` raises error

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/open.ribose.com#28]
Maybe related to #27 ?

```
bundle exec jekyll serve --trace
Configuration file: /Users/me/src/open.ribose.com/_config.yml
Configuration file: /Users/me/src/open.ribose.com/_config.yml
 Theme Config file: /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_config.yml
            Source: /Users/me/src/open.ribose.com
       Destination: /Users/me/src/open.ribose.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting '_projects/Metanorma/assets/css/style.scss':
                    File to import not found or unreadable: metanorma-rules. Load paths: /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_sass /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_sass /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_sass on line 16
bundler: failed to load command: jekyll (/Users/me/.rbenv/versions/2.6.5/bin/jekyll)
Jekyll::Converters::Scss::SyntaxError: File to import not found or unreadable: metanorma-rules.
Load paths:
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_sass
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_sass
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-theme-open-project-2.0.22/_sass on line 16
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:118:in `convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:101:in `block in convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:99:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:99:in `reduce'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:99:in `convert'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:83:in `render_document'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/renderer.rb:62:in `run'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:479:in `render_regenerated'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:463:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:463:in `block in render_docs'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:462:in `each_value'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:462:in `render_docs'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:191:in `render'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/site.rb:71:in `process'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/command.rb:28:in `process_site'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:65:in `build'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/commands/build.rb:36:in `process'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `block in start'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:93:in `start'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-3.8.7/exe/jekyll:15:in `<top (required)>'
  /Users/me/.rbenv/versions/2.6.5/bin/jekyll:23:in `load'
  /Users/me/.rbenv/versions/2.6.5/bin/jekyll:23:in `<top (required)>'
```

**Comment by strogonoff** [comment]
Fixed along with #27 by https://github.com/riboseinc/open.ribose.com/commit/c12d2517722609aa38bc504103d5bd419f86b512 and https://github.com/riboseinc/jekyll-theme-open-project-helpers/commit/9622075009a09c5edaeb24da08d894b7087df8e0. Production and local builds work, let me know if it doesn’t for you.

(Note: using Jekyll 4 now.)
